---

- name: download alertmanager binary
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: unpack alertmanager binaries
  unarchive:
    remote_src: true
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"

- name: propagate official alertmanager binary
  copy:
    remote_src: true
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: "{{ alertmanager_binary_install_dir }}/alertmanager"
    mode: 0755
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
  notify:
    - restart alertmanager
  become: true
  become_user: root
