---

- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
    system: true
  become: true
  become_user: root

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: true
  become_user: root

- name: Download node_exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  async: 600

- name: Unpack node_exporter binary
  unarchive:
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"

- name: Propagate node_exporter binaries
  copy:
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/bin/node_exporter"
    mode: 0755
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  notify: restart node_exporter
  become: true
  become_user: root
