---

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  become: true
  become_user: root

- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
  become: true
  become_user: root

- name: configure prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
  notify: restart prometheus
  become: true
  become_user: root

- name: copy custom alerting rule files
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/alert.rules"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
  notify: restart prometheus
  become: true
  become_user: root

- name: create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  notify: restart prometheus
