---

- name: download prometheus binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: unpack prometheus binaries
  unarchive:
    remote_src: true
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"

- name: propagate official prometheus and promtool binaries
  copy:
    remote_src: true
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus
  become: true
  become_user: root
