---

- name: Create the pve_exporter group
  group:
    name: "{{ pve_exporter_group }}"
    state: present
    system: true
  become: true
  become_user: root

- name: Create the pve_exporter user
  user:
    name: "{{ pve_exporter_user }}"
    group: "{{ pve_exporter_group }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: true
  become_user: root

- name: Install Pip
  apt:
    name: python-pip
    state: present
  become: true
  become_user: root

- name: Install the exporter
  pip:
    name: prometheus-pve-exporter
    state: present
  become: true
  become_user: root
